### ISSUE TITLE
Support Signed-Releases (npm)

### ISSUE THREAD

**Issue by willfarrell** [willfarrell/template-npm#15]
See https://github.com/ossf/scorecard/issues/4080

```yml
      - name: Pack
        run: |
          npm pack --json
      - uses: actions/attest-build-provenance@c074443f1aee8d4aeeae555aebba3282517141b2 # v2.2.3
        with:
          subject-path: ./**/*.tgz
```

Idea:
- make npm package
- send to https://github.com/willfarrell/template-npm/attestations
- make draft release
- attach files and signatures to release

Refs:
- https://trstringer.com/github-actions-create-release-upload-artifacts/
